### ISSUE TITLE
The dbm extension doesn't work

### ISSUE THREAD

**Issue by jpdeplaix** [ocsigen/ocsigenserver#26]
I wanted to test dbm as a replacement of sqlite for Cumulus and I ran into problem, first the configuration and the documentation is not very explicit and I don't really know what its configuration does exactly (or I didn't look very far).
Second, I tried with the following configuration:
```
<extension findlib-package="ocsigen.ext.ocsipersist-dbm">
  <store dir="/tmp"/>
  <ocsidbm name="ocsidbm"/>
</extension>
```
and when I run, I got the following console message:
```
ocsigenserver: main: Initializing Ocsipersist-dbm
ocsigenserver: main: Launching a new Ocsidbm process: ocsidbm on directory /tmp.
ocsigenserver: main: Launching a new Ocsidbm process: ocsidbm on directory /tmp.
```
and if I tried to load a page, it loops and gives nothing. If I ```^C``` the process, a zombie process remains and holds the network port.

**Comment by jpdeplaix** [comment]
Mmmh why this issue has been closed ? The documentation is not fixed :/

**Comment by Drup** [comment]
Hum ? It seemed the problem was solved. What should be changed in the doc ?

**Comment by jpdeplaix** [comment]
Well it worked for me because I changed the config but it still doesn't work using the config from the documentation.
